# Generated by Django 4.0.5 on 2023-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_question_img2_alter_question_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
    ]
